### ISSUE TITLE
REQUEST: New membership for @superbeeny

### ISSUE THREAD

**Issue by superbeeny** [radius-project/community#41]
Requirements
[X] I have reviewed the community membership guidelines.
[X] I have enabled 2FA on my GitHub account. See https://github.com/settings/security
[X] I have subscribed to the Radius Community Discord
[X] I am contributing 

List of contributions to the Radius project
PRs reviewed / authored
https://github.com/radius-project/docs/pull/1100
https://github.com/radius-project/radius/pull/7744

Issues responded to
https://github.com/radius-project/radius/issues/7561

cc @rynowak , @willtsai , @kachawla

**Comment by rynowak** [comment]
I'm supportive of adding @superbeeny as a member. He's been attending community calls, and has made some contributions both big and small 👍

**Comment by willtsai** [comment]
I am supportive as well and second all of @rynowak's points. In fact, @superbeeny presented at a previous community meeting, so I'm confident about the impact they will have on the Radius community.

**Comment by kachawla** [comment]
I support this as well for the reasons @rynowak and @willtsai captured above. Thanks @superbeeny for your continued contributions from bug fixes to new features!

**Comment by rynowak** [comment]
Closing this since we added @superbeeny as a member!
