### ISSUE TITLE
REQUEST: New membership for rynowak

### ISSUE THREAD

**Issue by rynowak** [radius-project/community#48]
### GitHub Username

`rynowak`

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/radius-project/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account, see https://github.com/settings/security
- [x] I have subscribed to the [Radius community Discord server](https://aka.ms/radius/discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more [Radius](https://github.com/radius-project) repositories

### List of contributions to the Radius project

I've been a core contributor to Radius for over two years 😁 

https://github.com/radius-project/radius/graphs/contributors

Hi all, I'm filling out one of these to formalize and document my involvement. We're working towards open-governance for Radius as an overall project and will be inviting the community to join. So we're publicly documenting our roles in the project that have been informal up to now. 

In terms of my role, I'm a maintainer for the following repos:

- `radius-project/radius`
- `radius-project/dashboard`
- `radius-project/bicep-types-aws`
- `radius-project/bicep` (soon to be deleted)
- `radius-project/design-notes`

**Comment by kachawla** [comment]
+1

**Comment by willtsai** [comment]
+1
