### ISSUE TITLE
REQUEST: New membership for brooke-hamilton

### ISSUE THREAD

**Issue by brooke-hamilton** [radius-project/community#51]
### GitHub Username

`brooke-hamilton`

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/radius-project/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account, see https://github.com/settings/security
- [x] I have subscribed to the [Radius community Discord server](https://aka.ms/radius/discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more [Radius](https://github.com/radius-project) repositories

### List of contributions to the Radius project

 - Author: https://github.com/radius-project/radius/pull/7722
 - Author: https://github.com/radius-project/docs/pull/1192
 - Author: https://github.com/radius-project/samples/pull/1649
 - Author: https://github.com/radius-project/samples/pull/1683
 - Author: https://github.com/radius-project/recipes/pull/71
 - Author: https://github.com/radius-project/docs/pull/1193
 - Author: https://github.com/radius-project/radius/pull/7962
 - Fixed: https://github.com/radius-project/radius/issues/7676
 - Fixed: https://github.com/radius-project/radius/issues/7637
 - Fixed: https://github.com/radius-project/radius/issues/7721
 - Reviewer: https://github.com/radius-project/design-notes/pull/63
 - Reviewer: https://github.com/radius-project/design-notes/pull/61
 - Reviewer: https://github.com/radius-project/design-notes/pull/60
 - Reviewer: https://github.com/radius-project/design-notes/pull/58
 - Reviewer: https://github.com/radius-project/design-notes/pull/57
 - Reviewer: https://github.com/radius-project/samples/pull/1746

### Sponsorship
@rynowak, @sylvainsf, @kachawla, @willtsai (maintainers on this repo), in accordance with the guidelines in the [community membership document](https://github.com/radius-project/community/blob/main/community-membership.md#requirements) please reply with +1 if you approve of membership. 👍 🍰

**Comment by rynowak** [comment]
+1

**Comment by willtsai** [comment]
+1

**Comment by willtsai** [comment]
Membership invite has been sent and accepted, thanks!
