### ISSUE TITLE
REQUEST: New membership for reshrahim

### ISSUE THREAD

**Issue by Reshrahim** [radius-project/community#53]
### GitHub Username

reshrahim

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/radius-project/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account, see https://github.com/settings/security
- [x] I have subscribed to the [Radius community Discord server](https://aka.ms/radius/discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more [Radius](https://github.com/radius-project) repositories

### List of contributions to the Radius project

- PRs reviewed / authored
   - https://github.com/radius-project/design-notes/pull/58
   - https://github.com/radius-project/design-notes/pull/55
   - https://github.com/radius-project/recipes/pull/63
   - https://github.com/radius-project/docs/pull/1138
   - https://github.com/radius-project/docs/pull/1190
- Issues responded to
   - https://github.com/radius-project/radius/issues/7960
   - https://github.com/radius-project/recipes/issues/77
   - https://github.com/radius-project/docs/issues/885
   - https://github.com/radius-project/docs/issues/970
   
I would like to be a MAINTAINER on the following repos
- /docs and /website: MAINTAINER
- /samples: MAINTAINER
- /recipes: MAINTAINER

and an APPROVER on the other repos to do the following 
   - Adding or removing `good-first-issues` labels on issues for the community to contribute. Editing the issue description to add more details on `good-first-issues`
   - Keep our issues and roadmap up to date for the community (close or reopen issues based on their completeness)
   - Review user facing changes in the main Radius repository

**Comment by willtsai** [comment]
+1 except for MAINTAINER role on `/recipes` - I think an APPROVER role for that repo might be more appropriate given sparser contribution history on the core `/recipes` code.

**Comment by rynowak** [comment]
+1 to MAINTAINER on docs. 

+1 to APPROVER on recipes and samples. We're looking for more direction-setting as the bar for maintainer. 

I think you've got a good opportunity to maintainer on Recipes as we flesh out the area more.

**Comment by sylvainsf** [comment]
+1 for MAINTAINER of Docs/Website, APPROVER for samples and recipes. The thinking is the bar for maintainership of samples and recipes would be someone doing stewardship of those resources such as proposing new samples, driving community effort or development around major recipe work, etc.
