### ISSUE TITLE
REQUEST: New membership for ryanwaite

### ISSUE THREAD

**Issue by ryanwaite** [radius-project/community#56]
### GitHub Username

@ryanwaite

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/radius-project/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account, see https://github.com/settings/security
- [x] I have subscribed to the [Radius community Discord server](https://aka.ms/radius/discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more [Radius](https://github.com/radius-project) repositories

### List of contributions to the Radius project

- PRs reviewed / authored
- Issues responded to

**Comment by willtsai** [comment]
+1 for Radius org membership role.

**Comment by kachawla** [comment]
+1 for Radius org membership role.

**Comment by rynowak** [comment]
+1 for Radius org membership role.
