### ISSUE TITLE
REQUEST: New membership for @nithyatsu

### ISSUE THREAD

**Issue by nithyatsu** [radius-project/community#57]
### GitHub Username

e.g. @nithyatsu 

### Requirements

- [ X] I have reviewed the [community membership guidelines](https://github.com/radius-project/community/blob/main/community-membership.md)
- [ X] I have enabled 2FA on my GitHub account, see https://github.com/settings/security
- [ X] I have subscribed to the [Radius community Discord server](https://aka.ms/radius/discord)
- [ X] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more [Radius](https://github.com/radius-project) repositories

### List of contributions to the Radius project

/radius: APPROVER (for areas of cli, observability, gateways, app graph and in general new APIs, workload identity)

- PRs reviewed / authored
about 160 PRs authored https://github.com/radius-project/radius/pulls?q=is%3Apr+is%3Aclosed+author%3Anithyatsu
- Issues responded to
created 114 issues, worked on issues related to cli, logging and tracing, gateways, application graph, ucp planes, workload identity - irsa.

/dashboard: APPROVER

I have contributed to only 3 PRs. I think I might be the only engineer on our team that worked on dashboard, therefore requesting approver status.

**Comment by sylvainsf** [comment]
I nominate and approve

**Comment by willtsai** [comment]
+1

**Comment by rynowak** [comment]
+1 for APPROVER on `radius` and `dashboard`
