### ISSUE TITLE
REQUEST: New membership for ytimocin

### ISSUE THREAD

**Issue by ytimocin** [radius-project/community#59]
### GitHub Username

@ytimocin 

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/radius-project/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account, see https://github.com/settings/security
- [x] I have subscribed to the [Radius community Discord server](https://aka.ms/radius/discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more [Radius](https://github.com/radius-project) repositories

### List of contributions to the Radius project

- /radius: **MAINTAINER**
  - PRs: https://github.com/radius-project/radius/pulls?q=is%3Apr+author%3Aytimocin+is%3Aclosed
  - Issues: https://github.com/radius-project/radius/issues/created_by/ytimocin (56 Open, 143 Closed)
- /samples: **MAINTAINER**
  - PRs: https://github.com/radius-project/samples/pulls?q=is%3Apr+is%3Aclosed+author%3Aytimocin
  - Issues: https://github.com/radius-project/samples/issues?q=is%3Aissue+author%3Aytimocin+is%3Aclosed
- /bicep-types-aws: **APPROVER**
  - PRs: https://github.com/radius-project/bicep-types-aws/pulls/ytimocin

AB#13509

**Comment by sylvainsf** [comment]
Nominated and approved.

**Comment by willtsai** [comment]
@ytimocin - can you please provide links to the example PRs and issues you've worked on directly for each of the repos you've requested MAINTAINER and APPROVER roles?

**Comment by ytimocin** [comment]
Removing the following: dashboard, docs and website, recipes.

**Comment by rynowak** [comment]
+1 for APPROVER on `radius` and `samples`

I'd like to see more strategic/directional work for maintainer status. I'm not sure you'd qualify for `bicep-types-aws` without a bigger body of work.

**Comment by sylvainsf** [comment]
+1 for APPROVER on radius & samples repos

**Comment by willtsai** [comment]
+1 on APPROVER role for `/radius` and `/sample` repos
Given that you've only contributed a single PR to `/bicep-types-aws`, I think there is a bit more to go for approvership
