### ISSUE TITLE
REQUEST: New membership for kachawla

### ISSUE THREAD

**Issue by kachawla** [radius-project/community#61]
### GitHub Username

@kachawla 

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/radius-project/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account, see https://github.com/settings/security
- [x] I have subscribed to the [Radius community Discord server](https://aka.ms/radius/discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more [Radius](https://github.com/radius-project) repositories

### List of contributions to the Radius project

I've been a core contributor to Radius for over two years: https://github.com/radius-project/radius/graphs/contributors. My contributions include leading design, implementation, and PR reviews across several components of the system, including but not limited to Recipes, portable resources, core applications RP, and Terraform. My contributions map to the following roles:

`radius-project/radius`: maintainer
`radius-project/recipes`: maintainer
`radius-project/design-notes`: maintainer
`radius-project/samples and docs`: approver

AB#13499

**Comment by willtsai** [comment]
+1

**Comment by sylvainsf** [comment]
+1

**Comment by rynowak** [comment]
+1 to all.
