### ISSUE TITLE
REQUEST: New membership for sk593

### ISSUE THREAD

**Issue by sk593** [radius-project/community#62]
### GitHub Username

@sk593

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/radius-project/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account, see https://github.com/settings/security
- [x] I have subscribed to the [Radius community Discord server](https://aka.ms/radius/discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more [Radius](https://github.com/radius-project) repositories

### List of contributions to the Radius project

- /radius: APPROVER
Authored [~120 PRs](https://github.com/radius-project/radius/pulls/sk593)
Opened [~50 issues](https://github.com/radius-project/radius/issues/created_by/sk593)
Key areas of work: Recipes, Bicep extensibility, Portable Resources, CLI, Terraform

- /bicep-types-aws: MAINTAINER
Refactored a lot of the repository code and workflows: https://github.com/radius-project/bicep-types-aws/pull/43 
I have also opened issues for errors in our workflows and PRs that I would like to fix, but would need maintainer-level status to do: https://github.com/radius-project/bicep-types-aws/issues/61 

AB#13500

**Comment by willtsai** [comment]
+1

**Comment by sylvainsf** [comment]
+1

**Comment by rynowak** [comment]
+1 to both
