### ISSUE TITLE
REQUEST: New membership for willdavsmith

### ISSUE THREAD

**Issue by willdavsmith** [radius-project/community#63]
### GitHub Username

@willdavsmith 

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/radius-project/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account, see https://github.com/settings/security
- [x] I have subscribed to the [Radius community Discord server](https://aka.ms/radius/discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more [Radius](https://github.com/radius-project) repositories

### List of contributions to the Radius project

- /radius: APPROVER
Authored [144 PRs](https://github.com/radius-project/radius/pulls?q=is%3Amerged+is%3Apr+author%3Awilldavsmith+)
Opened [132 issues](https://github.com/radius-project/radius/issues?q=is%3Aissue+author%3Awilldavsmith+)
Key areas of work: Networking (Applications.Core/Gateways), AWS support, release automation, test reliability, security (Workload Identity support), GitOps support

- /samples: MAINTAINER
Authored [42 PRs](https://github.com/radius-project/samples/pulls?q=is%3Amerged+is%3Apr+author%3Awilldavsmith+)
Opened [11 issues](https://github.com/radius-project/samples/issues?q=is%3Aissue+author%3Awilldavsmith+)
Key areas of work: Automated testing, testing reliability, rad-ification and recipe creation, release automation

- /bicep-types-aws: APPROVER
Authored [8 PRs](https://github.com/radius-project/bicep-types-aws/pulls?q=is%3Amerged+is%3Apr+author%3Awilldavsmith+)
Key areas of work: Maintenance of AWS Bicep types, maintenance of testing resources in AWS, maintenance of team security and credentials for AWS

- /recipes: APPROVER
Authored [9 PRs](https://github.com/radius-project/recipes/pulls?q=is%3Amerged+is%3Apr+author%3Awilldavsmith+)
Key areas of work: AWS support, rad-ifying sample applications

AB#13510

**Comment by sylvainsf** [comment]
+1

**Comment by rynowak** [comment]
+1
