### ISSUE TITLE
REQUEST: New membership for vishwahiremat

### ISSUE THREAD

**Issue by vishwahiremat** [radius-project/community#64]
### GitHub Username

@vishwahiremat

### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/radius-project/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account, see https://github.com/settings/security
- [x] I have subscribed to the [Radius community Discord server](https://aka.ms/radius/discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more [Radius](https://github.com/radius-project) repositories

### List of contributions to the Radius project

- /radius: APPROVER
  Authored: [~160PRs](https://github.com/radius-project/radius/pulls/vishwahiremat) 
  Opened: [~60 issues](https://github.com/radius-project/radius/issues/created_by/vishwahiremat)
  Key areas of work: Recipes, Portable Resources,Core RP resources(Application.Core/SecretStores),  CLI, Terraform, IRSA

- /recipes: APPROVER
  Authored: [3 PRs](https://github.com/radius-project/recipes/pulls?q=is%3Amerged+is%3Apr+author%3Avishwahiremat)
  Key areas of work: Added the test workflow to validate the recipes in this repo.

AB#13526

**Comment by willtsai** [comment]
+1

**Comment by sylvainsf** [comment]
+1

**Comment by rynowak** [comment]
+1
