### ISSUE TITLE
REQUEST: New membership for lakshmimsft

### ISSUE THREAD

**Issue by lakshmimsft** [radius-project/community#65]
### Requirements

- [x] I have reviewed the [community membership guidelines](https://github.com/radius-project/community/blob/main/community-membership.md)
- [x] I have enabled 2FA on my GitHub account, see https://github.com/settings/security
- [x] I have subscribed to the [Radius community Discord server](https://aka.ms/radius/discord)
- [x] I am contributing (any of the following apply: issues, discussions, PRs, reviews) to 1 or more [Radius](https://github.com/radius-project) repositories

### List of contributions to the Radius project

- PRs reviewed / authored
- /radius: MAINTAINER
Authored [101 PRs]
Reviewed [269 PRs]
Opened [58 issues]

- PRs reviewed / authored
- /samples: MAINTAINER/APPROVER
Authored [8 PRs]
Reviewed [20 PRs]
Opened [ 7 issues]

- PRs reviewed / authored
- /docs: APPROVER
Authored [11 PRs]
Reviewed [18 PRs]
Opened [ 6 issues]

- PRs reviewed / authored
- /recipes: MAINTAINER
Authored [2 PRs]
Reviewed [6 PRs]
Opened [ 0 issues]

AB#13529

**Comment by willtsai** [comment]
+1 APPROVER on `/radius` until more evidence of long-term planning/influence is demonstrated
+1 APPROVER on `/samples`
+1 APPROVER on `/docs`

Need more substantial contributions to the `/recipes` repo specifically before consideration for APPROVER role.

**Comment by sylvainsf** [comment]
+1 APPROVER on /radius until more evidence of long-term planning/influence is demonstrated
+1 APPROVER on /samples
+1 APPROVER on /docs

**Comment by rynowak** [comment]
+1 for APPROVER on `radius`, `samples`, and `docs`. For maintainer on Radius, I'd want to see more strategic or direction-setting work. I think you're on a good path to grow into this.
