### ISSUE TITLE
November 2nd 2023, Community Meeting Agenda

### ISSUE THREAD

**Issue by willtsai** [radius-project/community#7]
## 📞 Radius Community Meeting

Every month we host a [community meeting](https://github.com/radius-project/community/#community-meetings) to highlight community created content, showcase new features, review upcoming milestones, and engage in Q&A with the Radius community - all are welcome and encouraged to participate.

The purpose of this thread is to form a discussion amongst the Radius community on potential topics to highlight during the meeting. If you have a topic you wish to present or learn more about, please add a comment and be sure to include your name and a short description of the topic.

The conversations in this thread will directly influence the meeting agenda for the community call on October 31 2023, at 9 AM PST ([See it in your local time](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20231031T09&p1=234&msg=Radius+Community+Call)). The meeting agenda is finalized by a Community Call Host prior to the meeting.

See you at the community call! 👋

## Agenda

- Introduction
- Welcome to the Radius community
- Radius launch update
- Navigating Radius
- v0.26 release highlights + demos
- Open Discussion
- Closing

 <details>
    <summary>Checklists for the host</summary>

### Before the meeting

- [x] Find speakers
- [x] Collect Radius news (blog posts & videos found on social media, and show-and-tell Discord channel)
- [x] Prepare slide deck
- [x] Send meeting invite to the speakers

### During the meeting

- Welcome & announce that the meeting will be recorded
- Start the recording
- Show the agenda
- Welcome first speaker
- First session
- Q&A first session
- Welcome second speaker
- Second session
- Q&A second session
- Show Radius related news, posts, videos.
- Open discussion
- Closing & mention Radius Discord channel

### After the meeting

- [x] Upload the meeting to  the Teams drive and include:

  - [x] Read-only link to slides
  - [x] [Radius Discord link](https://discord.gg/WnWqYa6QTH)
  - [x] Other relevant links related to the sessions

- [x] Close this issue

</details>

**Comment by AaronCrawfis** [comment]
Recording from this community call: https://youtu.be/EfGAwli5W4U?si=FqSq_nt1bKrtNDm2

See you next time!
